{% set name = "pygeohydro" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 325440eab5e039db964c312bd754e67fa25e6517f6e24efdda593a99c476337b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - async-retriever >=0.3.12
    - cytoolz
    - dask-core
    - defusedxml
    - folium
    - geopandas >=0.10
    - h5netcdf
    - hydrosignatures >=0.1.12
    - lxml
    - matplotlib-base >=3.5
    - numpy >=1.21
    - pandas >=1.0
    - pygeoogc >=0.13.12
    - pygeoutils >=0.13.12
    - pynhd >=0.13.12
    - pyproj >=2.2
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8
    - ujson
    - xarray >=2022.03.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
