{% set name = "pygeohydro" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: b69d07c1c6d37581eb5f81d745c2780b083bb2fdee8aecab3e3a38bac4876e21

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever =0.15
    - cytoolz
    - dask-core
    - defusedxml
    - folium
    - geopandas >=0.10
    - h5netcdf
    - hydrosignatures =0.15
    - lxml
    - matplotlib-base >=3.5
    - numpy >=1.21
    - pandas >=1.0
    - pygeoogc =0.15
    - pygeoutils =0.15
    - pynhd =0.15
    - pyproj >=2.2
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8.5
    - ujson
    - xarray >=2022.03.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
