{% set name = "pygeohydro" %}
{% set version = "0.16.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: cf5dffa9c09938b958b4d921f541a56ecdf6924091c8b2d3149513a460e79359

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.17,>=0.16
    - cytoolz
    - defusedxml
    - folium
    - geopandas-base >=0.10
    - fiona
    - h5netcdf
    - hydrosignatures <0.17,>=0.16
    - lxml
    - matplotlib-base >=3.5
    - numpy >=1.21
    - pandas >=1.0
    - pygeoogc <0.17,>=0.16
    - pygeoutils <0.17,>=0.16
    - pynhd <0.17,>=0.16
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=2
    - ujson
    - xarray >=2023.01.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
