{% set name = "pygeohydro" %}
{% set version = "0.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 3e1f01dea49419360806bb43ff98e58a7aa1e64d1451dc785a561a89d354717b

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever
    - cytoolz
    - defusedxml
    - folium
    - geopandas
    - lxml
    - matplotlib-base
    - numpy
    - pandas
    - pygeoogc
    - pygeoutils
    - pynhd
    - python >=3.7
    - rasterio
    - shapely
    - xarray

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeohydro
  summary: Access geospatial hydrology web services through Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
