{% set name = "pygeohydro" %}
{% set version = "0.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 134151867342b53e370904437902fedad016cf64e8d6a87888ca55f14e5646cd

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3
    - cytoolz
    - defusedxml
    - folium
    - geopandas >=0.7
    - lxml
    - matplotlib-base >=3.0
    - numpy >=1.17
    - pandas >=1.0
    - pygeoogc >=0.12
    - pygeoutils >=0.12
    - pynhd >=0.12
    - python >=3.7
    - rasterio
    - scipy
    - shapely >=1.6
    - xarray >=0.18
    - importlib_metadata

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeohydro
  summary: Access geospatial hydrology web services through Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
