{% set name = "pygeohydro" %}
{% set version = "0.15.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 3e75c631ad0b560e52af54a0908f80c2f11d9bfcf31c72714e0262f82e4f2440

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - setuptools-scm >=7
    - pip
  run:
    - python >=3.8
    - async-retriever <0.16,>=0.15
    - cytoolz
    - dask-core
    - defusedxml
    - folium
    - geopandas >=0.10
    - h5netcdf
    - hydrosignatures <0.16,>=0.15
    - lxml
    - matplotlib-base >=3.5
    - numpy >=1.21
    - pandas >=1.0
    - pygeoogc <0.16,>=0.15.1
    - pygeoutils <0.16,>=0.15
    - pynhd <0.16,>=0.15.1
    - pyproj >=3.0.1
    - rasterio >=1.2
    - rioxarray >=0.11
    - scipy
    - shapely >=1.8.5
    - ujson
    - xarray >=2023.04.0

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
