{% set name = "pygeohydro" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: e9312f9e69649afaf1629c247abb141541aa808f0ec428cb39485e66ea633d83

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.2
    - cytoolz
    - defusedxml
    - folium
    - geopandas >=0.7
    - lxml
    - matplotlib-base
    - numpy >=1.17
    - pandas >=1.0
    - pygeoogc >=0.11
    - pygeoutils >=0.11
    - pynhd >=0.11
    - python >=3.7
    - rasterio
    - shapely >=1.6
    - xarray >=0.17

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeohydro
  summary: Access geospatial hydrology web services through Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
