{% set name = "pygeohydro" %}
{% set version = "0.13.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 65ecee59292fbe5f91e7119a4cb76ab49e0457130c253946aba4f85b440ebf34

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - defusedxml
    - pynhd >=0.13.5
    - lxml
    - pandas >=1.0
    - h5netcdf
    - geopandas >=0.8
    - scipy
    - numpy >=1.17
    - async_retriever >=0.3.5
    - shapely >=1.8
    - pygeoogc >=0.13.5
    - folium
    - rasterio >=1.2
    - cytoolz
    - xarray >=2022.03.0
    - pygeoutils >=0.13.5
    - proplot

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hyriver/pygeohydro
  summary: Access geospatial web services that offer hydrological data
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - cheginit
