{% set name = "pygeohydro" %}
{% set version = "0.13.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pygeohydro-{{ version }}.tar.gz
  sha256: 1f6ce19ac4557f5b5a26f991ca56a4cbbf1288f06ac09a3f033b2a974468cb02

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - async_retriever >=0.3.2
    - cytoolz
    - defusedxml
    - folium
    - geopandas >=0.7
    - h5netcdf
    - lxml
    - numpy >=1.17
    - pandas >=1.0
    - proplot
    - pygeoogc >=0.13.1
    - pygeoutils >=0.13.1
    - pynhd >=0.13.1
    - python >=3.7
    - rasterio
    - scipy
    - shapely >=1.7
    - xarray >=0.18
    - importlib_metadata

test:
  imports:
    - pygeohydro
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cheginit/pygeohydro
  summary: Access geospatial hydrology web services through Python
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cheginit
